services:
  composer:
    image: composer
    volumes:
      - ./backend:/app
      - ~/.ssh:/root/.ssh
      - ~/.composer:/tmp
    command: install

  composer-ludwig:
    image: composer
    volumes:
      - ./ludwig:/app
      - ~/.ssh:/root/.ssh
      - ~/.composer:/tmp
    command: install

  backend:
    image: ghcr.io/bravoure/lucy-development-php:8.3
    volumes:
      - ./backend:/var/www/backend
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      PHP_UPLOAD_MAX_FILESIZE: 128M
      PHP_POST_MAX_SIZE: 128M
      PHP_MAX_INPUT_VARS: 10000
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - database
      - redis
      - kibana

  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=craft
      - MYSQL_USER=craft
      - MYSQL_PASSWORD=craft
      - MYSQL_ROOT_PASSWORD=craft
    ports:
      - '3307:3306'
    volumes:
      - mysqlData:/var/lib/mysql
    command:
      - --sql_mode=
    depends_on:
      - database-ludwig

  database-ludwig:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
      - MYSQL_ROOT_PASSWORD=laravel
    ports:
      - '3308:3306'
    volumes:
      - mysqlDataLudwig:/var/lib/mysql
    command:
      - --sql_mode=

  ludwig:
    image: ghcr.io/bravoure/ludwig-development-php:8.3
    volumes:
      - ./ludwig:/var/www/ludwig
    depends_on:
      - queue-ludwig
      - elasticsearch

  queue-ludwig:
    image: ghcr.io/bravoure/ludwig-development-php:8.3
    command: sh -c 'sleep 5 && php ludwig/artisan queue:listen'
    restart: unless-stopped
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./ludwig:/var/www/ludwig

  webserver:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8000:8000"
    volumes:
      - ./backend:/var/www/backend:cached
      - ./ludwig:/var/www/ludwig:cached
      - ./config/webserver/local/:/etc/nginx/conf.d/
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - backend
      - queue
      - ludwig

  queue:
    image: ghcr.io/bravoure/lucy-development-php:8.3
    volumes:
      - ./backend:/app
    env_file: backend/.env
    command: sh -c 'sleep 30 && php craft queue/listen --verbose=1 --interactive=0 --isolate=1'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1024M
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    depends_on:
      - database
      - redis

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          memory: 128M
    logging:
      options:
        max-size: "1m"
        max-file: "3"

  php-cs-fixer:
    image: jakzal/phpqa:php8.2-alpine
    volumes:
      - ./backend:/backend
    command: php-cs-fixer fix
    working_dir: /backend

  php-cs-fixer-ludwig:
    image: jakzal/phpqa:php8.3-alpine
    volumes:
      - ./ludwig:/ludwig
    command: php-cs-fixer fix
    working_dir: /ludwig

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
volumes:
  mysqlDataLudwig:
    driver: local
  mysqlData:
    driver: local
  es_data:
    driver: local
